### PR TITLE
[TH DG] Normalized the Datomic URI code

### PR DESCRIPTION
**Pull request by danielglauser**
This normalizes the config to make it easier to test the system end-to-end for the upcoming election notification.

### CODE REVIEW

**Comment by danielglauser** [comment]
@ericnormand @cap10morgan @7maples @dcohen Would appreciate some eyes from some of you fine folks.

**Comment by dcohen** [comment]
LGTM.

**Comment by cap10morgan** [comment]
LGTM

**Comment by ericnormand** [comment]
LGTM

**Pull request merged**
