### PR TITLE
exclude nop and log4j libs from datomic & add logback

### PR DESCRIPTION
**Pull request by cap10morgan**
Without this I got nop logging (i.e. no log output) when I combined this
with another project in a docker-compose stack.

No card, just an opportunistic improvement.

### CODE REVIEW

**Comment by ericnormand** [comment]
LGTM.

**Comment by ericnormand** [comment]
How'd you figure that out?

**Comment by cap10morgan** [comment]
Oh, the significant difference here was not using WildFly. The Immutant docs says that outside of WildFly, it uses logback for logging, but inside WildFly it uses WildFly's logging subsystem. So that makes sense.

**Comment by cap10morgan** [comment]
@ericnormand [Datomic logging docs](http://docs.datomic.com/configuring-logging.html)

**Pull request merged**
